import json
import os
import re
import textwrap
from pathlib import Path, PurePosixPath

from conan import ConanFile
from conan.errors import ConanException, ConanInvalidConfiguration
from conan.tools.apple import is_apple_os
from conan.tools.build import check_min_cppstd, cross_building
from conan.tools.cmake import CMake, CMakeDeps, CMakeToolchain, cmake_layout
from conan.tools.files import (
    apply_conandata_patches,
    collect_libs,
    copy,
    export_conandata_patches,
    get,
    load,
    rename,
    replace_in_file,
    rm,
    rmdir,
    save,
)
from conan.tools.microsoft import is_msvc, msvc_runtime_flag
from conan.tools.scm import Version

required_conan_version = ">=1.62.0"


def components_from_dotfile(dotfile):
    """
    Parse the dotfile generated by the
    [cmake --graphviz](https://cmake.org/cmake/help/latest/module/CMakeGraphVizOptions.html)
    option to generate the list of available LLVM CMake targets and their inter-component dependencies.

    In future a [CPS](https://cps-org.github.io/cps/index.html) format could be used, or generated directly
    by the LLVM build system
    """

    def node_labels(dot):
        """
        match each node in the dotfile with a label property, and map the label to a conan component
        """
        label_replacements = {
            "LibXml2::LibXml2": "libxml2::libxml2",
            "ZLIB::ZLIB": "zlib::zlib",
            "zstd::libzstd_static": "zstd::zstdlib",
            "-lpthread": "pthread",
        }
        for row in dot:
            match_label = re.match(r"""^\s*"(node[0-9]+)"\s*\[\s*label\s*=\s*"(.+)".*""", row)
            if match_label:
                node = match_label.group(1)
                label = match_label.group(2)
                yield node, label_replacements.get(label, label)

    def node_dependencies(dot):
        """
        Using the nodes with labels, extract the component dependencies of each node
        """
        ignore_deps = [
            "diaguids.lib"  # https://github.com/llvm/llvm-project/issues/86250
        ]
        labels = {k: v for k, v in node_labels(dot)}
        for row in dot:
            match_dep = re.match(r"""^\s*"(node[0-9]+)"\s*->\s*"(node[0-9]+)".*""", row)
            if match_dep:
                node_label = labels[match_dep.group(1)]
                dependency = labels[match_dep.group(2)]
                if node_label.startswith("LLVM") and PurePosixPath(dependency).parts[-1] not in ignore_deps:
                    yield node_label, labels[match_dep.group(2)]
        # some components don't have dependencies
        for label in labels.values():
            if label.startswith("LLVM"):
                yield label, None

    system_libs = {
        "ole32",
        "delayimp",
        "shell32",
        "advapi32",
        "-delayload:shell32.dll",
        "uuid",
        "psapi",
        "-delayload:ole32.dll",
        "ntdll",
        "ws2_32",
        "rt",
        "m",
        "dl",
        "pthread",
    }
    components = {}
    dotfile_rows = dotfile.split("\n")
    for node, dependency in node_dependencies(dotfile_rows):
        key = "system_libs" if dependency in system_libs else "requires"
        if node not in components:
            components[node] = {"system_libs": [], "requires": []}
            if dependency is not None:
                components[node][key] = [dependency]
        elif dependency is not None:
            components[node][key].append(dependency)

    return components


class LLVMCoreConan(ConanFile):
    name = "llvm-core"
    description = "A toolkit for the construction of highly optimized compilers,optimizers, and runtime environments."
    package_type = "library"
    license = "Apache-2.0 WITH LLVM-exception"
    topics = ("llvm", "compiler")
    homepage = "https://llvm.org"
    url = "https://github.com/conan-io/conan-center-index"
    settings = "os", "arch", "compiler", "build_type"
    options = {
        "shared": [True, False],
        "fPIC": [True, False],
        "components": ["ANY"],
        "targets": ["ANY"],
        "tools": [True, False],
        "utils": [True, False],
        "exceptions": [True, False],
        "rtti": [True, False],
        "threads": [True, False],
        "lto": ["On", "Off", "Full", "Thin"],
        "static_stdlib": [True, False],
        "unwind_tables": [True, False],
        "expensive_checks": [True, False],
        "use_perf": [True, False],
        "backtraces": [True, False],
        "crash_overrides": [True, False],
        "use_sanitizer": [
            "Address",
            "Memory",
            "MemoryWithOrigins",
            "Undefined",
            "Thread",
            "DataFlow",
            "Address;Undefined",
            "None",
        ],
        "with_ffi": [True, False],
        "with_libedit": [True, False],
        "with_zlib": [True, False],
        "with_xml2": [True, False],
        "with_z3": [True, False],
        "with_zstd": [True, False],
    }
    default_options = {
        "shared": False,
        "fPIC": True,
        "components": "all",
        "targets": "all",
        "tools": True,
        "utils": True,
        "exceptions": True,
        "rtti": True,
        "threads": True,
        "lto": "Off",
        "static_stdlib": False,
        "unwind_tables": True,
        "expensive_checks": False,
        "use_perf": False,
        "backtraces": True,
        "crash_overrides": True,
        "use_sanitizer": "None",
        "with_libedit": True,
        "with_ffi": False,
        "with_xml2": True,
        "with_z3": True,
        "with_zlib": True,
        "with_zstd": True,
    }

    @property
    def _min_cppstd(self):
        # Read the required C++ standard straight from LLVM_REQUIRED_CXX_STANDARD in
        # llvm/CMakeLists.txt rather than hardcoding it. Only available after source().
        cmakelists = load(self, self._llvm_source_folder_path / "CMakeLists.txt")
        match = re.search(r"set\(LLVM_REQUIRED_CXX_STANDARD\s+(\d+)\)", cmakelists)
        if not match:
            raise ConanException("Could not parse LLVM_REQUIRED_CXX_STANDARD from LLVM's CMakeLists.txt")
        return int(match.group(1))

    @property
    def _compilers_minimum_version(self):
        # Parse the minimum host compilers from LLVM's own CheckCompilerVersion.cmake so
        # the recipe never drifts from upstream requirements. Only available after source().
        content = load(self, self._llvm_source_folder_path / "cmake" / "modules" / "CheckCompilerVersion.cmake")

        def minimum(variable):
            match = re.search(rf"set\({variable}\s+([0-9.]+)\)", content)
            return match.group(1) if match else None

        # CheckCompilerVersion records MSVC as an _MSC_VER value (e.g. 19.28); Conan's
        # "msvc" setting uses the toolset form (19.2x -> 192, 19.3x -> 193).
        msvc = minimum("MSVC_MIN")
        if msvc:
            major, _, minor = msvc.partition(".")
            msvc = f"{major}{minor[0]}" if minor else major

        return {
            "gcc": minimum("GCC_MIN"),
            "clang": minimum("CLANG_MIN"),
            "apple-clang": minimum("APPLECLANG_MIN"),
            "msvc": msvc,
        }

    def export_sources(self):
        export_conandata_patches(self)

    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC
            del self.options.with_libedit  # not supported on windows

    def configure(self):
        if self.options.shared:
            self.options.rm_safe("fPIC")

    def layout(self):
        cmake_layout(self, src_folder="src")

    def requirements(self):
        if self.options.with_ffi:
            self.requires("libffi/3.4.6")
        if self.options.get_safe("with_libedit"):
            self.requires("editline/3.1")
        if self.options.with_zlib:
            self.requires("zlib/[>=1.2.11 <2]")
        if self.options.with_xml2:
            self.requires("libxml2/[>=2.12.5 <3]")
        if self.options.with_z3:
            self.requires("z3/4.13.0")
        if self.options.get_safe("with_zstd"):
            self.requires("zstd/1.5.6")

    def build_requirements(self):
        self.tool_requires("ninja/[>=1.10.2 <2]")
        self.tool_requires("cmake/[>=3.20 <4]")  # LLVM 22 requires cmake >= 3.20.0

    def validate(self):
        # NOTE: the C++ standard and host-compiler minimums are enforced in generate(),
        # since they are parsed from the LLVM sources which only exist after source().
        if self.options.shared:
            if self.settings.os == "Windows":
                raise ConanInvalidConfiguration("Shared builds are currently not supported on Windows")
            if is_apple_os(self) and self.options.with_xml2 and bool(self.dependencies["libxml2"].options.iconv):
                # FIXME iconv contains duplicate symbols in the libiconv and libcharset libraries (both of which are
                #  provided by libiconv). This may be an issue with how conan packages libiconv
                raise ConanInvalidConfiguration(
                    "iconv cannot be linked into the shared LLVM library on macos "
                    "due to duplicate symbols. Use libxml2/*:iconv=False."
                )

        if self.options.exceptions and not self.options.rtti:
            raise ConanInvalidConfiguration("Cannot enable exceptions without rtti support")

        if cross_building(self):
            # FIXME support cross compilation
            #  For Cross Building, LLVM builds a "native" toolchain in a subdirectory of the main build directory.
            #  This subdirectory would need to have the conan cmake configuration files for the build platform
            #  installed into it for a cross build to be successful.
            #  see also https://llvm.org/docs/HowToCrossCompileLLVM.html
            raise ConanInvalidConfiguration("Cross compilation is not supported. Contributions are welcome!")

    def source(self):
        # LLVM >=22 no longer ships the per-component source tarballs (llvm-*/cmake-*),
        # only the full monorepo, which already contains llvm/ and cmake/ as siblings.
        # The build points straight at the llvm/ subfolder (see _llvm_source_folder_path).
        get(self, **self.conan_data["sources"][self.version]["llvm-project"], strip_root=True)

    def _apply_resource_limits(self, cmake_definitions):
        # LLVM links are memory-hungry; let constrained machines cap parallel job RAM via
        #   -c user.llvm-core:ram_per_compile_job=<MB> / ram_per_link_job=<MB>
        ram_per_compile_job = self.conf.get("user.llvm-core:ram_per_compile_job")
        if ram_per_compile_job:
            cmake_definitions["LLVM_RAM_PER_COMPILE_JOB"] = ram_per_compile_job

        ram_per_link_job = self.conf.get("user.llvm-core:ram_per_link_job")
        if ram_per_link_job:
            cmake_definitions["LLVM_RAM_PER_LINK_JOB"] = ram_per_link_job

    @property
    def _targets_to_build(self):
        return self.options.targets if self.options.targets != "all" else self._all_targets

    @property
    def _all_targets(self):
        # Read the canonical stable (non-experimental) target list straight from LLVM's
        # own CMakeLists.txt instead of maintaining a hardcoded copy that drifts between
        # releases (see the note near the top of this file).
        cmakelists = load(self, self._llvm_source_folder_path / "CMakeLists.txt")
        match = re.search(r"set\(LLVM_ALL_TARGETS\s+(.*?)\)", cmakelists, re.DOTALL)
        if not match:
            raise ConanException("Could not parse LLVM_ALL_TARGETS from LLVM's CMakeLists.txt")
        return ";".join(match.group(1).split())

    def _validate_toolchain(self):
        # C++ standard and host-compiler minimums are parsed from the LLVM sources, so
        # this runs from generate() (after source()) rather than validate().
        if self.settings.compiler.cppstd:
            check_min_cppstd(self, self._min_cppstd)
        minimum_version = self._compilers_minimum_version.get(str(self.settings.compiler))
        if minimum_version and Version(self.settings.compiler.version) < minimum_version:
            raise ConanInvalidConfiguration(
                f"{self.ref} requires {self.settings.compiler} >= {minimum_version} "
                f"(C++{self._min_cppstd}), which your compiler does not support."
            )

    def generate(self):
        self._validate_toolchain()
        tc = CMakeToolchain(self, generator="Ninja")
        # https://releases.llvm.org/22.1.0/docs/CMake.html
        cmake_variables = {
            # Enables LLVM to find conan libraries during try_compile
            "CMAKE_TRY_COMPILE_CONFIGURATION": str(self.settings.build_type),
            # LLVM has two separate concepts of a "shared library build".
            # "BUILD_SHARED_LIBS" builds shared versions of all the static components
            # "LLVM_BUILD_LLVM_DYLIB" builds a single shared library containing all components.
            # It is likely the latter that the user expects by a "shared library" build.
            "BUILD_SHARED_LIBS": False,
            "LLVM_BUILD_LLVM_DYLIB": self.options.shared,
            "LLVM_LINK_LLVM_DYLIB": self.options.shared,
            "LLVM_DYLIB_COMPONENTS": self.options.components,
            "LLVM_ABI_BREAKING_CHECKS": "WITH_ASSERTS",
            "LLVM_INCLUDE_BENCHMARKS": False,
            "LLVM_INCLUDE_TOOLS": self.options.tools,
            "LLVM_INCLUDE_UTILS": self.options.utils,
            "LLVM_INCLUDE_EXAMPLES": False,
            "LLVM_INCLUDE_TESTS": False,
            "LLVM_ENABLE_IDE": False,
            "LLVM_ENABLE_EH": self.options.exceptions,
            "LLVM_ENABLE_RTTI": self.options.rtti,
            "LLVM_ENABLE_THREADS": self.options.threads,
            "LLVM_ENABLE_LTO": self.options.lto,
            "LLVM_STATIC_LINK_CXX_STDLIB": self.options.static_stdlib,
            "LLVM_ENABLE_UNWIND_TABLES": self.options.unwind_tables,
            "LLVM_ENABLE_EXPENSIVE_CHECKS": self.options.expensive_checks,
            "LLVM_ENABLE_ASSERTIONS": str(self.settings.build_type),
            "LLVM_USE_PERF": self.options.use_perf,
            "LLVM_ENABLE_BACKTRACES": self.options.backtraces,
            "LLVM_ENABLE_CRASH_OVERRIDES": self.options.crash_overrides,
            "LLVM_ENABLE_BINDINGS": False,
            "LLVM_ENABLE_LIBPFM": False,
            "LLVM_ENABLE_LIBEDIT": self.options.get_safe("with_libedit", False),
            "LLVM_ENABLE_Z3_SOLVER": self.options.with_z3,
            "LLVM_ENABLE_FFI": self.options.with_ffi,
            "LLVM_ENABLE_ZLIB": "FORCE_ON" if self.options.with_zlib else False,
            "LLVM_ENABLE_LIBXML2": "FORCE_ON" if self.options.with_xml2 else False,
        }
        # LLVM_ENABLE_TERMINFO was removed in LLVM 19; only zstd is configurable now.
        cmake_variables["LLVM_ENABLE_ZSTD"] = "FORCE_ON" if self.options.with_zstd else False

        if self.options.targets != "all":
            cmake_variables["LLVM_TARGETS_TO_BUILD"] = self.options.targets

        if self.settings.os == "Windows":
            # LLVM-C.dll (the C API shared library) defaults ON on Windows and is a large
            # extra link. A static C++ consumer doesn't need it, so tie it to `tools`.
            cmake_variables["LLVM_BUILD_LLVM_C_DYLIB"] = self.options.tools

        self._apply_resource_limits(cmake_variables)

        if is_msvc(self):
            build_type = str(self.settings.build_type).upper()
            cmake_variables[f"LLVM_USE_CRT_{build_type}"] = msvc_runtime_flag(self)

        if not self.options.shared:
            cmake_variables.update(
                {"DISABLE_LLVM_LINK_LLVM_DYLIB": True, "LLVM_ENABLE_PIC": self.options.get_safe("fPIC", default=True)}
            )

        if self.options.use_sanitizer == "None":
            cmake_variables["LLVM_USE_SANITIZER"] = ""
        else:
            cmake_variables["LLVM_USE_SANITIZER"] = self.options.use_sanitizer

        if self.settings.os == "Linux":
            # Workaround for: https://github.com/conan-io/conan/issues/13560
            libdirs_host = [
                l
                for dependency in self.dependencies.host.values()
                for l in dependency.cpp_info.aggregated_components().libdirs
            ]
            tc.variables["CMAKE_BUILD_RPATH"] = ";".join(libdirs_host)

        tc.cache_variables.update(cmake_variables)
        tc.generate()

        deps = CMakeDeps(self)
        deps.generate()

    @property
    def _graphviz_file(self):
        return PurePosixPath(self.build_folder) / "llvm-core.dot"

    def build(self):
        apply_conandata_patches(self)
        cmake = CMake(self)
        graphviz_args = [f"--graphviz={self._graphviz_file}"]

        # components not exported or not of interest
        exclude_patterns = ["LLVMTableGenGlobalISel.*", "CONAN_LIB.*", "LLVMExegesis.*", "LLVMCFIVerify.*"]
        graphviz_options = textwrap.dedent(f"""
            set(GRAPHVIZ_EXECUTABLES OFF)
            set(GRAPHVIZ_MODULE_LIBS OFF)
            set(GRAPHVIZ_OBJECT_LIBS OFF)
            set(GRAPHVIZ_IGNORE_TARGETS "{";".join(exclude_patterns)}")
        """)
        save(self, PurePosixPath(self.build_folder) / "CMakeGraphVizOptions.cmake", graphviz_options)
        cmake.configure(build_script_folder="llvm", cli_args=graphviz_args)
        cmake.build()

    @property
    def _package_folder_path(self):
        return PurePosixPath(self.package_folder)

    @property
    def _llvm_source_folder_path(self):
        return PurePosixPath(self.source_folder) / "llvm"

    def _llvm_build_info(self):
        cmake_config = Path(self._package_folder_path / "lib" / "cmake" / "llvm" / "LLVMConfig.cmake").read_text(
            "utf-8"
        )
        components = components_from_dotfile(load(self, self._graphviz_file))

        return {
            "components": components,
            "native_arch": re.search(r"""^set\(LLVM_NATIVE_ARCH (\S*)\)$""", cmake_config, re.MULTILINE).group(1),
        }

    @property
    def _cmake_module_path(self):
        return PurePosixPath("lib") / "cmake" / "llvm"

    @property
    def _build_info_file(self):
        return self._package_folder_path / self._cmake_module_path / "conan_llvm_build_info.json"

    @property
    def _build_module_file_rel_path(self):
        return self._cmake_module_path / f"conan-official-{self.name}-variables.cmake"

    def _create_cmake_build_module(self, build_info, module_file):
        targets_with_jit = ["X86", "PowerPC", "AArch64", "ARM", "Mips", "SystemZ"]
        content = textwrap.dedent(f"""\
            set(LLVM_TOOLS_BINARY_DIR "${{CMAKE_CURRENT_LIST_DIR}}/../../../bin")
            cmake_path(NORMAL_PATH LLVM_TOOLS_BINARY_DIR)
            set(LLVM_PACKAGE_VERSION "{self.version}")
            set(LLVM_AVAILABLE_LIBS "{";".join(build_info["components"].keys())}")
            set(LLVM_BUILD_TYPE "{self.settings.build_type}")
            set(LLVM_CMAKE_DIR "${{CMAKE_CURRENT_LIST_DIR}}")
            list(APPEND CMAKE_MODULE_DIR ${{CMAKE_CURRENT_LIST_DIR}})
            set(LLVM_ALL_TARGETS "{self._all_targets}")
            set(LLVM_TARGETS_TO_BUILD "{self._targets_to_build}")
            set(LLVM_TARGETS_WITH_JIT "{";".join(targets_with_jit)}")
            set(LLVM_NATIVE_ARCH "{build_info["native_arch"]}")
            set_property(GLOBAL PROPERTY LLVM_TARGETS_CONFIGURED On)
            set_property(GLOBAL PROPERTY LLVM_COMPONENT_LIBS ${{LLVM_AVAILABLE_LIBS}})
            if (NOT TARGET intrinsics_gen)
              add_custom_target(intrinsics_gen)
            endif()
            if (NOT TARGET omp_gen)
              add_custom_target(omp_gen)
            endif()
            if (NOT TARGET acc_gen)
              add_custom_target(acc_gen)
            endif()
           """)
        save(self, module_file, content)

    def _write_build_info(self):
        build_info = self._llvm_build_info()
        with open(self._build_info_file, "w", encoding="utf-8") as fp:
            json.dump(build_info, fp, indent=2)

        return build_info

    def _read_build_info(self) -> dict:
        with open(self._build_info_file, encoding="utf-8") as fp:
            return json.load(fp)

    def package(self):
        copy(self, "LICENSE.TXT", self._llvm_source_folder_path, self._package_folder_path / "licenses")
        cmake = CMake(self)
        cmake.install()

        build_info = self._write_build_info()

        cmake_folder = self._package_folder_path / "lib" / "cmake" / "llvm"
        rm(self, "LLVMConfig.cmake", cmake_folder)
        rm(self, "LLVMExports*", cmake_folder)
        rm(self, "Find*", cmake_folder)
        rm(self, "*.pdb", self._package_folder_path / "lib")
        rm(self, "*.pdb", self._package_folder_path / "bin")
        # need to rename this as Conan will flag it, but it's not actually a Config file and is needed by
        # downstream packages
        rename(self, cmake_folder / "LLVM-Config.cmake", cmake_folder / "LLVM-ConfigInternal.cmake")
        replace_in_file(self, cmake_folder / "AddLLVM.cmake", "LLVM-Config", "LLVM-ConfigInternal")
        rmdir(self, self._package_folder_path / "share")
        if self.options.shared:
            rm(self, "*.a", self._package_folder_path / "lib")

        self._create_cmake_build_module(build_info, self._package_folder_path / self._build_module_file_rel_path)

    def package_info(self):
        self.cpp_info.set_property("cmake_file_name", "LLVM")
        self.cpp_info.set_property(
            "cmake_build_modules",
            [self._build_module_file_rel_path, self._cmake_module_path / "LLVM-ConfigInternal.cmake"],
        )
        self.cpp_info.builddirs.append(self._cmake_module_path)

        if not self.options.shared:
            build_info = self._read_build_info()
            components = build_info["components"]

            for component_name, data in components.items():
                self.cpp_info.components[component_name].set_property("cmake_target_name", component_name)
                self.cpp_info.components[component_name].libs = [component_name]
                self.cpp_info.components[component_name].requires = data["requires"]
                self.cpp_info.components[component_name].system_libs = data["system_libs"]
        else:
            self.cpp_info.set_property("cmake_target_name", "LLVM")
            self.cpp_info.libs = collect_libs(self)
